updated

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,10 +45,10 @@ jobs:
       - name: Install SonarScanner
         run: |
             curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
-            unzip sonar-scanner.zip
-            sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
-            echo "export PATH=\$PATH:/opt/sonar-scanner/bin" >> ~/.bashrc
-            echo "/opt/sonar-scanner/bin" >> $GITHUB_PATH
+            unzip sonar-scanner.zip || (echo "Failed to unzip SonarScanner" && exit 1)
+            mv sonar-scanner-* sonar-scanner
+            echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH
+        
         
       - name: Verify SonarScanner
         run: /opt/sonar-scanner/bin/sonar-scanner -v
