updated

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,7 +45,7 @@ jobs:
       - name: Install SonarScanner
         run: |
             curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
-            unzip sonar-scanner.zip || (echo "Failed to unzip SonarScanner" && exit 1)
+            sonar-scanner-cli-5.0.1.3006-linux.zip || (echo "Failed to unzip SonarScanner" && exit 1)
             mv sonar-scanner-* sonar-scanner
             echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH
         
